#!/bin/bash -l

set -e -x

export GOROOT=$(readlink -nf /var/vcap/packages/golang_1.3)
export PATH=/var/vcap/packages/git/bin:${PATH}
export PATH=${GOROOT}/bin:${PATH}

export GOPATH=$PWD
go get -t -u -v github.com/amitkgupta/goodlearnbenchmarks/... || true
go install github.com/onsi/ginkgo/ginkgo

cd $GOPATH/src/github.com/amitkgupta/goodlearnbenchmarks
ginkgo -r -keepGoing
